version: '3'
services:

  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
      # - "./cv.sql:/docker-entrypoint-initdb.d/cv.sql"
    networks:
      - directus
    environment:
      POSTGRES_USER: 'cv'
      POSTGRES_PASSWORD: 'passwd'
      POSTGRES_DB: 'cv'

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      - database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      PUBLIC_URL: 'http://localhost:8055'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'cv'
      DB_USER: 'cv'
      DB_PASSWORD: 'passwd'

      CACHE_ENABLED: 'false'

      ADMIN_EMAIL: 'loys@loys.me'
      ADMIN_PASSWORD: 'passwd'

      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'
      # PUBLIC_URL: 'https://ddoirectus.example.com'


volumes:
  database:
  uploads:


networks:
  directus:
    #   traefik:
    #     external: true
