jenkins:
  systemMessage: "Natural Presence - One click to go"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          name: Admin
          password: passwd

  remotingSecurity:
    enabled: true

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git

jobs:
  - file: /var/jenkins_home/config/job.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: docker_hub_token
              secret: Alta*r667!!
              description: "Docker Hub password (so secure)."

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

unclassified:
  location:
    adminAddress: "acid@Wh4N05.biz"
    url: "http://localhost:8080/"
